### ISSUE TITLE
「Webで開く」と「statuses」の間にニコる・Boostの反映時刻差が存在する

### ISSUE THREAD

**Issue by nyango** [dwango/mastodon#17]
正常にニコれてBoost出来ているTOOT
https://friends.nico/@EzoeRyou/433052
![2017-04-21 9 48 05](https://cloud.githubusercontent.com/assets/3069291/25258117/1444c87a-2678-11e7-80c1-0f9d8dc5ef82.png)

同じTOOTを「Webで開く」で見たもの
https://friends.nico/web/statuses/433052
![2017-04-21 9 48 20](https://cloud.githubusercontent.com/assets/3069291/25258107/f3b9aa08-2677-11e7-9be7-55d7053ca64b.png)

**Comment by nyango** [comment]
あれ、今見たら治ってる。何だったんだ…

**Comment by nyango** [comment]
以下二点が同時刻の表示になりますので、時間差が発生してそうです。
![Uploading スクリーンショット 2017-04-21 9.58.10.png…]()
![2017-04-21 9 58 18](https://cloud.githubusercontent.com/assets/3069291/25258282/1ee29d7e-2679-11e7-8b1a-b8124067f1c1.png)

**Comment by masarakki** [comment]
時間の差とブースト/ニコル数の差?

**Comment by nyango** [comment]
issue立てた時点で、
https://friends.nico/@EzoeRyou/433052 だと「ブースト/ニコる＝2/5」な一方、
https://friends.nico/web/statuses/433052 だと「ブースト/ニコる＝0/0」になっていました。

後者のリンクも時間が経てば「ブースト/ニコる」の表示が正常になったのですが、
前者のリンクの方が反映されるのが早かったという話でした。

**Comment by masarakki** [comment]
ほーーーちょっと調べてみる
とはいえこの辺はいじってないので本体側の問題だと思う
