### ISSUE TITLE
メールアドレスで"+"が認識されない

### ISSUE THREAD

**Issue by ptrdiff-t** [dwango/mastodon#220]
メールアドレスに+を含めると、形式的には正しいメアドのはずなのに正しくないと怒られる。

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by masarakki** [comment]
スパム防止のため禁止してます
