### ISSUE TITLE
開発環境の auth/sign_in で「We're sorry, but something went wrong.」

### ISSUE THREAD

**Issue by narupo** [dwango/mastodon#32]
開発環境を docker-compose up 後、トップページからサインインページ（/auth/sign_in）に移動したところ、以下のエラーメッセージが表示されました。

```
We're sorry, but something went wrong.
```

コンソールのログ。

```
method=GET path=/auth/sign_in format=html controller=Auth::SessionsController action=new status=500 error='ActionView::Template::Error: undefined local variable or method `user_niconico_omniauth_authorize_path' for #<#<Class:0x00>:0x00>' duration=xxx view=xxx db=xxx
```

起動中のコンテナ mastodon_web_1 にアタッチ後 `./app/views/auth/shared/_omniauth.html.haml` 内のコードを削除。各コンテナをCtrl+Cで停止。docker-compose up で再起動後、 /auth/sign_in にアクセスするとサインインページが表示されてブラウザからサインイン出来るようになりました。

**Comment by narupo** [comment]
こちらの環境構築にミスがあったのかもしれないですが一応投稿。

**Comment by masarakki** [comment]
これニコニコのOAuthの設定しないとダメなんですけど外部公開してないのでどうしようか
とりあえず ENV['OMNIAUTH']  = 'niconico.hoge,hage' って書いとけばなんとかなると思う

**Comment by masarakki** [comment]
ちがった niconico:hoge:hage だ

**Comment by narupo** [comment]
`.env.production`ファイルの末尾に`OMNIAUTH=niconico:hoge:hage`の追加でエラー出なくなりました。
