### ISSUE TITLE
niconicoアカウントでのログインでログイン後に必ず/web/getting-startedにリダイレクトされる

### ISSUE THREAD

**Issue by rinsuki** [dwango/mastodon#40]
サードパーティのアプリ認証でログインするときなどにこういう挙動をすると少し不便です

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by masarakki** [comment]
なるほど 普通どうしてるんだろう

**Comment by masarakki** [comment]
def after_sign_in_path_for(_resource)
     last_url = stored_location_for(:user)

     if [about_path].include?(last_url)
       root_path
     else
       last_url || root_path
     end
   end

この当たりか

**Comment by masarakki** [comment]
これ本体も上手く動いてないな
```ruby
   def store_current_location
     store_location_for(:user, request.url)
   end
```
これが必ず /about を保存してしまう
