### ISSUE TITLE
ニコニコ動画サムネイルを表示するようにしてほしい

### ISSUE THREAD

**Issue by ghost** [dwango/mastodon#46]
Twitterカードの様にニコニコ動画に投稿された動画のサムネイルをトゥートの下あたりに表示してほしい。

**Comment by masarakki** [comment]
問題2つあって

- サムネhttpsで出せるか (サムネ配信サーバの処理能力の問題)
- ogタグのキャッシュ他のサービスでどうやってんの?

あたりをちょいと調べないといかん
