### ISSUE TITLE
README.md など開発者向けドキュメントを充実させたい

### ISSUE THREAD

**Issue by terashishi** [dwango/mastodon#58]
もっと活発になって欲しい

独自の機能・文化を一覧化しておきたい。
せめてREADME.md に http://dic.nicovideo.jp/a/friends.nico のリンクなどあってもいいのでは

**Comment by masarakki** [comment]
1.4.1 マージしたあとにやりますー

**Comment by masarakki** [comment]
ちょっと増やした
