### ISSUE TITLE
ローカルタイムライン上の発言への正規表現フィルター

### ISSUE THREAD

**Issue by narupo** [dwango/mastodon#66]
欲しがってる人を多数見かけました。

**Comment by masarakki** [comment]
HOMEじゃなくてLTLでやりたいってことなのか

**Comment by narupo** [comment]
LTLで需要があるみたいです
今はわかりませんが、Issue投稿当時に議論を見かけました

**Comment by takayamaki** [comment]
そういえばこれ、既に本家で実装されたものがfriends.nicoにも降りてきてるのでcloseしてよいのでは
