### ISSUE TITLE
ニコニコ独自の自動リンク対象の文字列がURLのクエリ内に含まれると壊れる

### ISSUE THREAD

**Issue by Petitsurume** [dwango/mastodon#76]
https://friends.nico/@petitsurume/16537089
投稿内容は`http://nico.ms/?sm9`
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by masarakki** [comment]
これもう治ってるやつだよね?
